### ISSUE TITLE
Cannot install with Homebrew

### ISSUE THREAD

**Issue by roeeyn** [hughbien/thyme#1]
Hi, thanks for creating this project. It is just what I need. Unfortunately, I cannot install it with Homebrew.
This is the error it throws:

![image](https://user-images.githubusercontent.com/13385000/116280752-a0ae5780-a74e-11eb-8d4d-a20ad0554dc6.png)

My setup is the following:
- Homebrew 3.1.3 (`brew doctor` throws no errors)
- Macos Catalina 10.15.7

Any suggestion on how to proceed?

**Comment by hughbien** [comment]
It looks like `Process.kill` was deprecated for `Process.signal` in Crystal v1.0.0. I went ahead and released a new version of Thyme (v0.1.5) which fixes that issue.

Try running `brew install hughbien/tap/thyme` and it should work this time. Let me know if it doesn't.

**Comment by roeeyn** [comment]
Thanks for the quick response. Now, it throws the following error:

![image](https://user-images.githubusercontent.com/13385000/116768120-fa867a00-a9f9-11eb-96d7-82cc227abc85.png)

do I really need to install the whole XCode for this?

**Comment by hughbien** [comment]
Crystal Lang is a requirement, but the Command Line Tools should be enough without Xcode.

That error message is unexpected though, because if you got the previous error (undefined method `kill`) that means you should already have Crystal 1.0 installed. I'm not sure why it's asking for Xcode now.

When you run `crystal -v`, does it show v1.0.0?

Some options that might work if you already have Crystal installed:

* `brew install hughbien/tap/thyme --without-crystal`
* `git clone https://github.com/hughbien/thyme.git && cd thyme && make build install`

If Crystal isn't installed yet, you'll need to get it here: <https://crystal-lang.org/install/on_mac_os/> until I can figure out why it's trying to install Xcode as a dependency.

**Comment by roeeyn** [comment]
> When you run crystal -v, does it show v1.0.0?

Yes, it says `Crystal 1.0.0 (2021-03-22)`

> `brew install hughbien/tap/thyme --without-crystal`

It throws the following:

![image](https://user-images.githubusercontent.com/13385000/117334271-6c7a1b80-ae5f-11eb-9b3b-2a63bd7a75b0.png)

Thanks for the help!

**Comment by hughbien** [comment]
Sorry for the delay on this! It looks like the build is having trouble finding the `shards` binary, most likely due to it being shimmed. I added a `HOMEBREW_SHARDS` env var option to help with it:

```
HOMEBREW_SHARDS=`which shards` brew install hughbien/tap/thyme --without-crystal
```

Hopefully that helps!

**Comment by hughbien** [comment]
Sorry for the delay on this!

It turns out Homebrew runs in a new process without shims loaded, so if you have Crystal installed as a shim the formula will fail. I added a few options to solve this.

If you have Crystal v1.0.0 installed via Asdf, you can run:

```
HOMEBREW_BIN=$(asdf which crystal)/../../embedded/bin HOMEBREW_CRYSTAL_PATH=`crystal env CRYSTAL_PATH` brew install hughbien/tap/thyme --without-crystal
```

If you installed Crystal v1.0.0 manually via a tarball (or a version manager that uses symbolic links):

```
HOMEBREW_BIN=$(which crystal)/.. brew install hughbien/tap/thyme --without-crystal
```

You can also install it manually via:

```
git clone https://github.com/hughbien/thyme.git
cd thyme
make
make install
```

Hopefully that helps and thanks for the bug report!

**Comment by roeeyn** [comment]
Hey 👋🏼  I just updated to big sur, and tried `brew install hughbien/tap/thyme` and worked with no issues at all. With this, I will proceed to close this issue as I'm not able to reproduce the error anymore. Thanks for this awesome tool 🍅 !
