### ISSUE TITLE
 a couple of enhancements

### ISSUE THREAD

**Issue by carlocaione** [hughbien/thyme#12]
I really like this small app, really useful.
I think that it is missing a couple of features though.

1) loop. It is really annoying that the application quit after the time expires.
2) hook on break starting (to have notification)
3) long break after $n short breaks.

**Comment by codeinabox** [comment]
:+1:

**Comment by hughbien** [comment]
Thanks for the feedback!

1) I've just added this to the latest gem v0.0.15: `thyme --repeat` to repeat indefinitely, `thyme --repeat 5` to loop 5 times.

2) Breaks trigger the before/after hooks, you can check to `@break` variable to see whether it's in break or work mode.

3) I don't have plans on adding long breaks since I usually walk away from my laptop for them. But doing this in `thymerc` works:

    before do
      # on every fourth run, set the break timer to 30 minutes
      timer_break = @repeat_index % 4 == 0 ? 5*60 : 30*60
      set :timer_break, timer_break
    end
